import { Providers } from "./providers";
import "./globals.css";
import { poppins } from "./fonts";

export const metadata = {
  title: "Illuminated",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${poppins.variable}`}>
      <head>
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/icon?family=Material+Icons'
        />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
